---
title: "Method1_Quantile_Regression"
output: html_document
---

# Set Up

## Load packages

```{r}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readr)
library(readxl)
library(splines)
library(mgcv)
library(ggcorrplot)
library(table1)
library(cowplot)
library(ggplot2)
library(Qtools)
library(quantreg)
library(broom)
```

## Setting template

```{r}
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "right"))
 
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Load dataset

```{r}
eqi_lbw_clean_df = 
  read_csv("data/eqi_lbw_clean_df.csv") |> 
  mutate(cat_rucc = factor(cat_rucc, levels = c("metropolitan-urbanized", "less urbanized", "thinly populated", "nonmetropolitan-urbanized")))
```

# EQI 25th 
```{r}
Mods25_eqi <- rq.counts(num_low_birthweight_births ~ eqi + cat_rucc + perc_smokers + perc_age1849, 
            data = eqi_lbw_clean_df, tau= 0.25, offset= log_live_births, alpha =0.05)

summary.rq(Mods25_eqi)
```

#EQI 50th 
```{r}
Mods50_eqi <- rq.counts(num_low_birthweight_births ~ eqi + cat_rucc + perc_smokers + perc_age1849, 
            data = eqi_lbw_clean_df, tau= 0.50, offset= log_live_births, alpha =0.05)
summary.rq(Mods50_eqi)
```

#EQI 75th 
```{r}
Mods75_eqi <- rq.counts(num_low_birthweight_births ~ eqi + cat_rucc + perc_smokers + perc_age1849, 
            data = eqi_lbw_clean_df, tau= 0.75, offset= log_live_births, alpha =0.05)
summary.rq(Mods75_eqi)
```

# Sociod 25 
```{r}
Mods25_sociod <- rq.counts(num_low_birthweight_births ~ sociod + cat_rucc + perc_smokers + perc_age1849, 
            data = eqi_lbw_clean_df, tau= 0.25, offset= log_live_births, alpha =0.05)
summary.rq(Mods25_sociod)
```

# Sociod 50 
```{r}
Mods50_sociod <- rq.counts(num_low_birthweight_births ~ sociod + cat_rucc + perc_smokers + perc_age1849, 
            data = eqi_lbw_clean_df, tau= 0.50, offset= log_live_births, alpha =0.05)
summary.rq(Mods50_sociod)
```

# Sociod 75 
```{r}
Mods75_sociod <- rq.counts(num_low_birthweight_births ~ sociod + cat_rucc + perc_smokers + perc_age1849, 
            data = eqi_lbw_clean_df, tau= 0.75, offset= log_live_births, alpha =0.05)
summary.rq(Mods75_sociod)
```

# Water 25 
```{r}
Mods25_water <- rq.counts(num_low_birthweight_births ~ water + cat_rucc + perc_smokers + perc_age1849, 
            data = eqi_lbw_clean_df, tau= 0.25, offset= log_live_births, alpha =0.05)
summary.rq(Mods25_water)
```

# Water 50 
```{r}
Mods50_water <- rq.counts(num_low_birthweight_births ~ water + cat_rucc + perc_smokers + perc_age1849, 
            data = eqi_lbw_clean_df, tau= 0.50, offset= log_live_births, alpha =0.05)
summary.rq(Mods50_water)
```

# Water 75 
```{r}
Mods75_water <- rq.counts(num_low_birthweight_births ~ water + cat_rucc + perc_smokers + perc_age1849, 
            data = eqi_lbw_clean_df, tau= 0.75, offset= log_live_births, alpha =0.05)
summary.rq(Mods75_water)
```

# Air 25 
```{r}
Mods25_air <- rq.counts(num_low_birthweight_births ~ air + cat_rucc + perc_smokers + perc_age1849, 
            data = eqi_lbw_clean_df, tau= 0.25, offset= log_live_births, alpha =0.05)
summary.rq(Mods25_air)
```

# Air 50 
```{r}
Mods50_air <- rq.counts(num_low_birthweight_births ~ air + cat_rucc + perc_smokers + perc_age1849, 
            data = eqi_lbw_clean_df, tau= 0.50, offset= log_live_births, alpha =0.05)
summary.rq(Mods50_air)
```

# Air 75 
```{r}
Mods75_air <- rq.counts(num_low_birthweight_births ~ air + cat_rucc + perc_smokers + perc_age1849, 
            data = eqi_lbw_clean_df, tau= 0.75, offset= log_live_births, alpha =0.05)
summary.rq(Mods75_air)
```

# Built 25 
```{r}
Mods25_built <- rq.counts(num_low_birthweight_births ~ built + cat_rucc + perc_smokers + perc_age1849, 
            data = eqi_lbw_clean_df, tau= 0.25, offset= log_live_births, alpha =0.05)
summary.rq(Mods25_built)
```

# Built 50 
```{r}
Mods50_built <- rq.counts(num_low_birthweight_births ~ built + cat_rucc + perc_smokers + perc_age1849, 
            data = eqi_lbw_clean_df, tau= 0.50, offset= log_live_births, alpha =0.05)
summary.rq(Mods50_built)
```

# Built 75
```{r}
Mods75_built <- rq.counts(num_low_birthweight_births ~ built + cat_rucc + perc_smokers + perc_age1849, 
            data = eqi_lbw_clean_df, tau= 0.75, offset= log_live_births, alpha =0.05)
summary.rq(Mods75_built)
```

# Land 25
```{r}
Mods25_land <- rq.counts(num_low_birthweight_births ~ land + cat_rucc + perc_smokers + perc_age1849, 
            data = eqi_lbw_clean_df, tau= 0.25, offset= log_live_births, alpha =0.05)
summary.rq(Mods25_land)
```

# Land 50
```{r}
Mods50_land <- rq.counts(num_low_birthweight_births ~ land + cat_rucc + perc_smokers + perc_age1849, 
            data = eqi_lbw_clean_df, tau= 0.50, offset= log_live_births, alpha =0.05)
summary.rq(Mods50_land)
```

# Land75
```{r}
Mods75_land <- rq.counts(num_low_birthweight_births ~ land + cat_rucc + perc_smokers + perc_age1849, 
            data = eqi_lbw_clean_df, tau= 0.75, offset= log_live_births, alpha =0.05)
summary.rq(Mods75_land)
```

# Summaries 

```{r}
summary25_eqi <- summary.rq(Mods25_eqi, alpha = 0.05)
summary50_eqi <- summary.rq(Mods50_eqi, alpha = 0.05)
summary75_eqi <- summary.rq(Mods75_eqi, alpha = 0.05)
summary25_air <- summary.rq(Mods25_air, alpha = 0.05)
summary50_air <- summary.rq(Mods50_air, alpha = 0.05)
summary75_air <- summary.rq(Mods75_air, alpha = 0.05)
summary25_water <- summary.rq(Mods25_water, alpha = 0.05)
summary50_water <- summary.rq(Mods50_water, alpha = 0.05)
summary75_water <- summary.rq(Mods75_water, alpha = 0.05)
summary25_land <- summary.rq(Mods25_land, alpha = 0.05)
summary50_land <- summary.rq(Mods50_land, alpha = 0.05)
summary75_land <- summary.rq(Mods75_land, alpha = 0.05)
summary25_built <- summary.rq(Mods25_built, alpha = 0.05)
summary50_built <- summary.rq(Mods50_built, alpha = 0.05)
summary75_built <- summary.rq(Mods75_built, alpha = 0.05)
summary25_sociod <- summary.rq(Mods25_sociod, alpha = 0.05)
summary50_sociod <- summary.rq(Mods50_sociod, alpha = 0.05)
summary75_sociod <- summary.rq(Mods75_sociod, alpha = 0.05)
```

#Extracting upper and lower limits 
```{r}
# Coeff.land.25 <- summary25_land$coefficients[2,]
land.25.Beta.pm.fit <- summary25_land$coefficients[2,1]
land.25.Beta.pm.se  <- summary25_land$coefficients[2,2]
land.25.Beta.pm.lci <- land.25.Beta.pm.fit - 1.96 * land.25.Beta.pm.se
land.25.Beta.pm.uci <- land.25.Beta.pm.fit + 1.96 * land.25.Beta.pm.se
```

```{r}
#Coeff.land.50 <- summary50_land)$coefficients[2,]
land.50.Beta.pm.fit <- summary50_land$coefficients[2,1]
land.50.Beta.pm.se  <- summary50_land$coefficients[2,2]
land.50.Beta.pm.lci <- land.50.Beta.pm.fit - 1.96 * land.50.Beta.pm.se
land.50.Beta.pm.uci <- land.50.Beta.pm.fit + 1.96 * land.50.Beta.pm.se
```

```{r}
#Coeff.land.75 <- summary75_land)$coefficients[2,]
land.75.Beta.pm.fit <- summary75_land$coefficients[2,1]
land.75.Beta.pm.se  <- summary75_land$coefficients[2,2]
land.75.Beta.pm.lci <- land.75.Beta.pm.fit - 1.96 * land.75.Beta.pm.se
land.75.Beta.pm.uci <- land.75.Beta.pm.fit + 1.96 * land.75.Beta.pm.se
```

```{r}
Coeff.air.25 <- summary(summary25_air)$coefficients[2,]
air.25.Beta.pm.fit <- summary(summary25_air)$coefficients[2,1]
air.25.Beta.pm.se  <- summary(summary25_air)$coefficients[2,2]
air.25.Beta.pm.lci <- air.25.Beta.pm.fit - 1.96 * air.25.Beta.pm.se
air.25.Beta.pm.uci <- air.25.Beta.pm.fit + 1.96 * air.25.Beta.pm.se
```

```{r}
Coeff.air.50 <- summary(summary50_air)$coefficients[2,]
air.50.Beta.pm.fit <- summary(summary50_air)$coefficients[2,1]
air.50.Beta.pm.se  <- summary(summary50_air)$coefficients[2,2]
air.50.Beta.pm.lci <- air.50.Beta.pm.fit - 1.96 * air.50.Beta.pm.se
air.50.Beta.pm.uci <- air.50.Beta.pm.fit + 1.96 * air.50.Beta.pm.se
```

```{r}
Coeff.air.75 <- summary(summary75_air)$coefficients[2,]
air.75.Beta.pm.fit <- summary(summary75_air)$coefficients[2,1]
air.75.Beta.pm.se  <- summary(summary75_air)$coefficients[2,2]
air.75.Beta.pm.lci <- air.75.Beta.pm.fit - 1.96 * air.75.Beta.pm.se
air.75.Beta.pm.uci <- air.75.Beta.pm.fit + 1.96 * air.75.Beta.pm.se
```

```{r}
Coeff.water.25 <- summary(summary25_water)$coefficients[2,]
water.25.Beta.pm.fit <- summary(summary25_water)$coefficients[2,1]
water.25.Beta.pm.se  <- summary(summary25_water)$coefficients[2,2]
water.25.Beta.pm.lci <- water.25.Beta.pm.fit - 1.96 * water.25.Beta.pm.se
water.25.Beta.pm.uci <- water.25.Beta.pm.fit + 1.96 * water.25.Beta.pm.se
```

```{r}
Coeff.water.50 <- summary(summary50_water)$coefficients[2,]
water.50.Beta.pm.fit <- summary(summary50_water)$coefficients[2,1]
water.50.Beta.pm.se  <- summary(summary50_water)$coefficients[2,2]
water.50.Beta.pm.lci <- water.50.Beta.pm.fit - 1.96 * water.50.Beta.pm.se
water.50.Beta.pm.uci <- water.50.Beta.pm.fit + 1.96 * water.50.Beta.pm.se
```

```{r}
Coeff.water.75 <- summary(summary75_water)$coefficients[2,]
water.75.Beta.pm.fit <- summary(summary75_water)$coefficients[2,1]
water.75.Beta.pm.se  <- summary(summary75_water)$coefficients[2,2]
water.75.Beta.pm.lci <- water.75.Beta.pm.fit - 1.96 * water.75.Beta.pm.se
water.75.Beta.pm.uci <- water.75.Beta.pm.fit + 1.96 * water.75.Beta.pm.se
```

```{r}
Coeff.built.25 <- summary(summary25_built)$coefficients[2,]
built.25.Beta.pm.fit <- summary(summary25_built)$coefficients[2,1]
built.25.Beta.pm.se  <- summary(summary25_built)$coefficients[2,2]
built.25.Beta.pm.lci <- built.25.Beta.pm.fit - 1.96 * built.25.Beta.pm.se
built.25.Beta.pm.uci <- built.25.Beta.pm.fit + 1.96 * built.25.Beta.pm.se
```

```{r}
Coeff.built.50 <- summary(summary50_built)$coefficients[2,]
built.50.Beta.pm.fit <- summary(summary50_built)$coefficients[2,1]
built.50.Beta.pm.se  <- summary(summary50_built)$coefficients[2,2]
built.50.Beta.pm.lci <- built.50.Beta.pm.fit - 1.96 * built.50.Beta.pm.se
built.50.Beta.pm.uci <- built.50.Beta.pm.fit + 1.96 * built.50.Beta.pm.se
```

```{r}
Coeff.built.75 <- summary(summary75_built)$coefficients[2,]
built.75.Beta.pm.fit <- summary(summary75_built)$coefficients[2,1]
built.75.Beta.pm.se  <- summary(summary75_built)$coefficients[2,2]
built.75.Beta.pm.lci <- built.75.Beta.pm.fit - 1.96 * built.75.Beta.pm.se
built.75.Beta.pm.uci <- built.75.Beta.pm.fit + 1.96 * built.75.Beta.pm.se
```

```{r}
Coeff.sociod.25 <- summary(summary25_sociod)$coefficients[2,]
sociod.25.Beta.pm.fit <- summary(summary25_sociod)$coefficients[2,1]
sociod.25.Beta.pm.se  <- summary(summary25_sociod)$coefficients[2,2]
sociod.25.Beta.pm.lci <- sociod.25.Beta.pm.fit - 1.96 * sociod.25.Beta.pm.se
sociod.25.Beta.pm.uci <- sociod.25.Beta.pm.fit + 1.96 * sociod.25.Beta.pm.se
```

```{r}
Coeff.sociod.50 <- summary(summary50_sociod)$coefficients[2,]
sociod.50.Beta.pm.fit <- summary(summary50_sociod)$coefficients[2,1]
sociod.50.Beta.pm.se  <- summary(summary50_sociod)$coefficients[2,2]
sociod.50.Beta.pm.lci <- sociod.50.Beta.pm.fit - 1.96 * sociod.50.Beta.pm.se
sociod.50.Beta.pm.uci <- sociod.50.Beta.pm.fit + 1.96 * sociod.50.Beta.pm.se
```

```{r}
Coeff.sociod.75 <- summary(summary75_sociod)$coefficients[2,]
sociod.75.Beta.pm.fit <- summary(summary75_sociod)$coefficients[2,1]
sociod.75.Beta.pm.se  <- summary(summary75_sociod)$coefficients[2,2]
sociod.75.Beta.pm.lci <- sociod.75.Beta.pm.fit - 1.96 * sociod.75.Beta.pm.se
sociod.75.Beta.pm.uci <- sociod.75.Beta.pm.fit + 1.96 * sociod.75.Beta.pm.se
```

```{r}
Coeff.eqi.25 <- summary(summary25_eqi)$coefficients[2,]
eqi.25.Beta.pm.fit <- summary(summary25_eqi)$coefficients[2,1]
eqi.25.Beta.pm.se  <- summary(summary25_eqi)$coefficients[2,2]
eqi.25.Beta.pm.lci <- eqi.25.Beta.pm.fit - 1.96 * eqi.25.Beta.pm.se
eqi.25.Beta.pm.uci <- eqi.25.Beta.pm.fit + 1.96 * eqi.25.Beta.pm.se
```

```{r}
Coeff.eqi.50 <- summary(summary50_eqi)$coefficients[2,]
eqi.50.Beta.pm.fit <- summary(summary50_eqi)$coefficients[2,1]
eqi.50.Beta.pm.se  <- summary(summary50_eqi)$coefficients[2,2]
eqi.50.Beta.pm.lci <- eqi.50.Beta.pm.fit - 1.96 * eqi.50.Beta.pm.se
eqi.50.Beta.pm.uci <- eqi.50.Beta.pm.fit + 1.96 * eqi.50.Beta.pm.se
```

```{r}
Coeff.eqi.75 <- summary(summary75_eqi)$coefficients[2,]
eqi.75.Beta.pm.fit <- summary(summary75_eqi)$coefficients[2,1]
eqi.75.Beta.pm.se  <- summary(summary75_eqi)$coefficients[2,2]
eqi.75.Beta.pm.lci <- eqi.75.Beta.pm.fit - 1.96 * eqi.75.Beta.pm.se
eqi.75.Beta.pm.uci <- eqi.75.Beta.pm.fit + 1.96 * eqi.75.Beta.pm.se
```

# Summaries 

```{r}
land_Model25th   <- cbind(land.25.Beta.pm.fit, land.25.Beta.pm.se, land.25.Beta.pm.lci, land.25.Beta.pm.uci)
land_Model50th   <- c(summary50_land$coefficients[2,1:3])
land_Model75th   <- c(summary75_land$coefficients[2,1:3])
```

```{r}
water_Model25th   <- c(summary25_water$coefficients[2,1:3])
water_Model50th   <- c(summary50_water$coefficients[2,1:3])
water_Model75th   <- c(summary75_water$coefficients[2,1:3])
```

```{r}
air_Model25th   <- c(summary25_air$coefficients[2,1:3])
air_Model50th   <- c(summary50_air$coefficients[2,1:3])
air_Model75th   <- c(summary75_air$coefficients[2,1:3])
```

```{r}
sociod_Model25th   <- c(summary25_sociod$coefficients[2,1:3])
sociod_Model50th   <- c(summary50_sociod$coefficients[2,1:3])
sociod_Model75th   <- c(summary75_sociod$coefficients[2,1:3])
```

```{r}
eqi_Model25th   <- c(summary25_eqi$coefficients[2,1:3])
eqi_Model50th   <- c(summary50_eqi$coefficients[2,1:3])
eqi_Model75th   <- c(summary75_eqi$coefficients[2,1:3])
```

```{r}
#land_coeff.table <- rbind(land_Model25th, land_Model50th, land_Model75th)
land_coeff.table <- as.data.frame(land_Model25th, stringsAsFactors = FALSE)

# set names for dataframe

names(land_coeff.table) <- c("coeff", "se","lci", "uci")
land_coeff.table        <- land_coeff.table %>% 
                      mutate(ModelName = c("land_Model 25th")) 

#  Plot

land_ForestPlot.25.50.75 <- ggplot(data=land_coeff.table, # defines what dataset we are using
             aes(x=ModelName,  # defines variable for the x axis
                 y=coeff,      # defines the variable for the point along the y axis
                 ymin=lci,     # defines the lower bound of the confidence interval
                 ymax=uci)) +  # define the upper bound of the confidence interval   
  geom_pointrange() +          # creates a point (y) with line defined by ymin and ymax        
  geom_errorbar()+             # creates lines with bars
  geom_hline(aes(yintercept=0.0), lty=2) + # add a dashed line at y=0 
  xlab("Model Name") +         # labels for axes
  ylab(expression("Coefficient for Land"~" (95% CI)"))

land_ForestPlot.25.50.75
```

```{r}
air_coeff.table <- rbind(air_Model75th, air_Model75th, air_Model75th)
air_coeff.table <- as.data.frame(air_coeff.table, stringsAsFactors = FALSE)

# set names for dataframe

names(air_coeff.table) <- c("coeff", "lci", "uci")
air_coeff.table        <- air_coeff.table %>% 
                      mutate(ModelName = c("air_Model 25th", "air_Model 50th", "air_Model 75th")) 

#  Plot

air_ForestPlot.25.50.75 <- ggplot(data=coeff.table, # defines what dataset we are using
             aes(x=ModelName,  # defines variable for the x axis
                 y=coeff,      # defines the variable for the point along the y axis
                 ymin=lci,     # defines the lower bound of the confidence interval
                 ymax=uci)) +  # define the upper bound of the confidence interval   
  geom_pointrange() +          # creates a point (y) with line defined by ymin and ymax        
  geom_errorbar()+             # creates lines with bars
  geom_hline(aes(yintercept=0.0), lty=2) + # add a dashed line at y=0 
  xlab("Model Name") +         # labels for axes
  ylab(expression("Coefficient for Air"~" (95% CI)"))

air_ForestPlot.25.50.75
```


```{r}
water_coeff.table <- rbind(water_Model75th, water_Model75th, water_Model75th)
water_coeff.table <- as.data.frame(water_coeff.table, stringsAsFactors = FALSE)

# set names for dataframe

names(water_coeff.table) <- c("coeff", "lci", "uci")
water_coeff.table        <- water_coeff.table %>% 
                      mutate(ModelName = c("water_Model 25th", "water_Model 50th", "water_Model 75th")) 

#  Plot

water_ForestPlot.25.50.75 <- ggplot(data=coeff.table, # defines what dataset we are using
             aes(x=ModelName,  # defines variable for the x axis
                 y=coeff,      # defines the variable for the point along the y axis
                 ymin=lci,     # defines the lower bound of the confidence interval
                 ymax=uci)) +  # define the upper bound of the confidence interval   
  geom_pointrange() +          # creates a point (y) with line defined by ymin and ymax        
  geom_errorbar()+             # creates lines with bars
  geom_hline(aes(yintercept=0.0), lty=2) + # add a dashed line at y=0 
  xlab("Model Name") +         # labels for axes
  ylab(expression("Coefficient for Water"~" (95% CI)"))

water_ForestPlot.25.50.75
```

```{r}
built_coeff.table <- rbind(built_Model75th, built_Model75th, built_Model75th)
built_coeff.table <- as.data.frame(built_coeff.table, stringsAsFactors = FALSE)

# set names for dataframe

names(built_coeff.table) <- c("coeff", "lci", "uci")
built_coeff.table        <- land_coeff.table %>% 
                      mutate(ModelName = c("built_Model 25th", "built_Model 50th", "built_Model 75th")) 

#  Plot

built_ForestPlot.25.50.75 <- ggplot(data=coeff.table, # defines what dataset we are using
             aes(x=ModelName,  # defines variable for the x axis
                 y=coeff,      # defines the variable for the point along the y axis
                 ymin=lci,     # defines the lower bound of the confidence interval
                 ymax=uci)) +  # define the upper bound of the confidence interval   
  geom_pointrange() +          # creates a point (y) with line defined by ymin and ymax        
  geom_errorbar()+             # creates lines with bars
  geom_hline(aes(yintercept=0.0), lty=2) + # add a dashed line at y=0 
  xlab("Model Name") +         # labels for axes
  ylab(expression("Coefficient for Built"~" (95% CI)"))

built_ForestPlot.25.50.75
```

```{r}
sociod_coeff.table <- rbind(sociod_Model75th, sociod_Model75th, sociod_Model75th)
sociod_coeff.table <- as.data.frame(sociod_coeff.table, stringsAsFactors = FALSE)

# set names for dataframe

names(sociod_coeff.table) <- c("coeff", "lci", "uci")
sociod_coeff.table        <- sociod_coeff.table %>% 
                      mutate(ModelName = c("sociod_Model 25th", "sociod_Model 50th", "sociod_Model 75th")) 

#  Plot

sociod_ForestPlot.25.50.75 <- ggplot(data=coeff.table, # defines what dataset we are using
             aes(x=ModelName,  # defines variable for the x axis
                 y=coeff,      # defines the variable for the point along the y axis
                 ymin=lci,     # defines the lower bound of the confidence interval
                 ymax=uci)) +  # define the upper bound of the confidence interval   
  geom_pointrange() +          # creates a point (y) with line defined by ymin and ymax        
  geom_errorbar()+             # creates lines with bars
  geom_hline(aes(yintercept=0.0), lty=2) + # add a dashed line at y=0 
  xlab("Model Name") +         # labels for axes
  ylab(expression("Coefficient for Sociod"~" (95% CI)"))

sociod_ForestPlot.25.50.75
```

```{r}
eqi_coeff.table <- rbind(eqi_Model75th, eqi_Model75th, eqi_Model75th)
eqi_coeff.table <- as.data.frame(eqi_coeff.table, stringsAsFactors = FALSE)

# set names for dataframe

names(eqi_coeff.table) <- c("coeff", "lci", "uci")
eqi_coeff.table        <- eqi_coeff.table %>% 
                      mutate(ModelName = c("eqi_Model 25th", "eqi_Model 50th", "eqi_Model 75th")) 

#  Plot

eqi_ForestPlot.25.50.75 <- ggplot(data=coeff.table, # defines what dataset we are using
             aes(x=ModelName,  # defines variable for the x axis
                 y=coeff,      # defines the variable for the point along the y axis
                 ymin=lci,     # defines the lower bound of the confidence interval
                 ymax=uci)) +  # define the upper bound of the confidence interval   
  geom_pointrange() +          # creates a point (y) with line defined by ymin and ymax        
  geom_errorbar()+             # creates lines with bars
  geom_hline(aes(yintercept=0.0), lty=2) + # add a dashed line at y=0 
  xlab("Model Name") +         # labels for axes
  ylab(expression("Coefficient for EQI"~" (95% CI)"))

eqi_ForestPlot.25.50.75
```

